// Copyright ©2014 The bíogo Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package graphic_test

import (
	"bytes"
	"flag"
	"io"
	"io/ioutil"
	"path/filepath"
	"testing"

	"github.com/biogo/ncbi/blast"
	"github.com/biogo/ncbi/blast/graphic"

	"github.com/gonum/plot/vg"
	"github.com/gonum/plot/vg/vgsvg"

	"gopkg.in/check.v1"
)

var regen = flag.Bool("regen", false, "regenerate golden images")

// Tests
func Test(t *testing.T) { check.TestingT(t) }

type S struct{}

var _ = check.Suite(&S{})

func intPtr(i int) *int          { return &i }
func stringPtr(s string) *string { return &s }

var testOutputs = []struct {
	in blast.Output
	cf func(w, h vg.Length) vg.Canvas

	configure bool
	legend    bool
	aligns    bool
	depths    bool

	golden string
}{
	{
		in: blast.Output{
			Program:   "blastn",
			Version:   "BLASTN 2.2.27+",
			Reference: "Stephen F. Altschul, Thomas L. Madden, Alejandro A. Sch&auml;ffer, Jinghui Zhang, Zheng Zhang, Webb Miller, and David J. Lipman (1997), \"Gapped BLAST and PSI-BLAST: a new generation of protein database search programs\", Nucleic Acids Res. 25:3389-3402.",
			Database:  "nr",
			QueryId:   "33421",
			QueryDef:  "No definition line",
			QueryLen:  32,
			QuerSeq:   nil,
			Parameters: blast.Parameters{
				MatrixName:  nil,
				Expect:      1000,
				Include:     nil,
				Match:       intPtr(1),
				Mismatch:    intPtr(-3),
				GapOpen:     5,
				GapExtend:   2,
				Filter:      stringPtr("F"),
				PhiPattern:  nil,
				EntrezQuery: nil,
			},
			Iterations: []blast.Iteration{
				{
					N:        1,
					QueryId:  stringPtr("33421"),
					QueryDef: stringPtr("No definition line"),
					QueryLen: intPtr(32),
					Hits: []blast.Hit{
						{
							N:         1,
							Id:        "gi|388525227|gb|CP003531.1|",
							Def:       "Thermogladius cellulolyticus 1633, complete genome",
							Accession: "CP003531",
							Len:       1356318,
							Hsps: []blast.Hsp{
								{
									N:              1,
									BitScore:       38.1576,
									Score:          19,
									EValue:         1.72292,
									QueryFrom:      7,
									QueryTo:        29,
									HitFrom:        1187458,
									HitTo:          1187436,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(-1),
									HspIdentity:    intPtr(22),
									HspPositive:    intPtr(22),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(23),
									Density:        nil,
									QuerySeq:       []byte("TGTCGAACTATACGACGAGCACT"),
									SubjectSeq:     []byte("TGTCGAGCTATACGACGAGCACT"),
									FormatMidline:  []byte("|||||| ||||||||||||||||"),
								},
							},
						},
						{
							N:         2,
							Id:        "gi|354799811|gb|JN964312.1|",
							Def:       "Mus musculus targeted non-conditional, lacZ-tagged mutant allele Morn4:tm1e(KOMP)Wtsi; transgenic",
							Accession: "JN964312",
							Len:       40247,
							Hsps: []blast.Hsp{
								{
									N:              1,
									BitScore:       36.1753,
									Score:          18,
									EValue:         6.80792,
									QueryFrom:      1,
									QueryTo:        18,
									HitFrom:        26580,
									HitTo:          26597,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(1),
									HspIdentity:    intPtr(18),
									HspPositive:    intPtr(18),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(18),
									Density:        nil,
									QuerySeq:       []byte("ACAGAATGTCGAACTATA"),
									SubjectSeq:     []byte("ACAGAATGTCGAACTATA"),
									FormatMidline:  []byte("||||||||||||||||||"),
								},
							},
						},
						{
							N:         24,
							Id:        "gi|356871506|emb|FO082053.1|",
							Def:       "Pichia sorbitophila strain CBS 7064 chromosome G complete sequence",
							Accession: "FO082053",
							Len:       1423303,
							Hsps: []blast.Hsp{
								{
									N:              1,
									BitScore:       32.2105,
									Score:          16,
									EValue:         106.294,
									QueryFrom:      13,
									QueryTo:        28,
									HitFrom:        61730,
									HitTo:          61745,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(1),
									HspIdentity:    intPtr(16),
									HspPositive:    intPtr(16),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(16),
									Density:        nil,
									QuerySeq:       []byte("ACTATACGACGAGCAC"),
									SubjectSeq:     []byte("ACTATACGACGAGCAC"),
									FormatMidline:  []byte("||||||||||||||||"),
								},
							},
						},
						{
							N:         25,
							Id:        "gi|353230524|emb|HE601625.1|",
							Def:       "Schistosoma mansoni strain Puerto Rico chromosome 2, complete genome",
							Accession: "HE601625",
							Len:       34464480,
							Hsps: []blast.Hsp{
								{
									N:              1,
									BitScore:       32.2105,
									Score:          16,
									EValue:         106.294,
									QueryFrom:      1,
									QueryTo:        16,
									HitFrom:        28173004,
									HitTo:          28173019,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(1),
									HspIdentity:    intPtr(16),
									HspPositive:    intPtr(16),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(16),
									Density:        nil,
									QuerySeq:       []byte("ACAGAATGTCGAACTA"),
									SubjectSeq:     []byte("ACAGAATGTCGAACTA"),
									FormatMidline:  []byte("||||||||||||||||"),
								},
								{
									N:              2,
									BitScore:       32.2105,
									Score:          16,
									EValue:         106.294,
									QueryFrom:      3,
									QueryTo:        18,
									HitFrom:        28996063,
									HitTo:          28996048,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(-1),
									HspIdentity:    intPtr(16),
									HspPositive:    intPtr(16),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(16),
									Density:        nil,
									QuerySeq:       []byte("AGAATGTCGAACTATA"),
									SubjectSeq:     []byte("AGAATGTCGAACTATA"),
									FormatMidline:  []byte("||||||||||||||||"),
								},
							},
						},
						{
							N:         26,
							Id:        "gi|341821300|emb|HE576794.1|",
							Def:       "Megasphaera elsdenii strain DSM 20460 draft genome",
							Accession: "HE576794",
							Len:       2474718,
							Hsps: []blast.Hsp{
								{
									N:              1,
									BitScore:       32.2105,
									Score:          16,
									EValue:         106.294,
									QueryFrom:      14,
									QueryTo:        29,
									HitFrom:        1741778,
									HitTo:          1741793,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(1),
									HspIdentity:    intPtr(16),
									HspPositive:    intPtr(16),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(16),
									Density:        nil,
									QuerySeq:       []byte("CTATACGACGAGCACT"),
									SubjectSeq:     []byte("CTATACGACGAGCACT"),
									FormatMidline:  []byte("||||||||||||||||"),
								},
							},
						},
					},
					Statistics: &blast.Statistics{
						DbNum:    17331862,
						DbLen:    1419046940,
						HspLen:   0,
						EffSpace: 0,
						Kappa:    0.710603,
						Lambda:   1.37406,
						Entropy:  1.30725,
					},
					Message: nil,
				},
			},
			MegaStatistics: nil,
		},
		cf:     func(w, h vg.Length) vg.Canvas { return vgsvg.New(w, h) },
		golden: "all.svg",
	},
	{
		in: blast.Output{
			Program:   "blastn",
			Version:   "BLASTN 2.2.27+",
			Reference: "Stephen F. Altschul, Thomas L. Madden, Alejandro A. Sch&auml;ffer, Jinghui Zhang, Zheng Zhang, Webb Miller, and David J. Lipman (1997), \"Gapped BLAST and PSI-BLAST: a new generation of protein database search programs\", Nucleic Acids Res. 25:3389-3402.",
			Database:  "nr",
			QueryId:   "33421",
			QueryDef:  "No definition line",
			QueryLen:  32,
			QuerSeq:   nil,
			Parameters: blast.Parameters{
				MatrixName:  nil,
				Expect:      1000,
				Include:     nil,
				Match:       intPtr(1),
				Mismatch:    intPtr(-3),
				GapOpen:     5,
				GapExtend:   2,
				Filter:      stringPtr("F"),
				PhiPattern:  nil,
				EntrezQuery: nil,
			},
			Iterations: []blast.Iteration{
				{
					N:        1,
					QueryId:  stringPtr("33421"),
					QueryDef: stringPtr("No definition line"),
					QueryLen: intPtr(32),
					Hits: []blast.Hit{
						{
							N:         1,
							Id:        "gi|388525227|gb|CP003531.1|",
							Def:       "Thermogladius cellulolyticus 1633, complete genome",
							Accession: "CP003531",
							Len:       1356318,
							Hsps: []blast.Hsp{
								{
									N:              1,
									BitScore:       38.1576,
									Score:          19,
									EValue:         1.72292,
									QueryFrom:      7,
									QueryTo:        29,
									HitFrom:        1187458,
									HitTo:          1187436,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(-1),
									HspIdentity:    intPtr(22),
									HspPositive:    intPtr(22),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(23),
									Density:        nil,
									QuerySeq:       []byte("TGTCGAACTATACGACGAGCACT"),
									SubjectSeq:     []byte("TGTCGAGCTATACGACGAGCACT"),
									FormatMidline:  []byte("|||||| ||||||||||||||||"),
								},
							},
						},
						{
							N:         2,
							Id:        "gi|354799811|gb|JN964312.1|",
							Def:       "Mus musculus targeted non-conditional, lacZ-tagged mutant allele Morn4:tm1e(KOMP)Wtsi; transgenic",
							Accession: "JN964312",
							Len:       40247,
							Hsps: []blast.Hsp{
								{
									N:              1,
									BitScore:       36.1753,
									Score:          18,
									EValue:         6.80792,
									QueryFrom:      1,
									QueryTo:        18,
									HitFrom:        26580,
									HitTo:          26597,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(1),
									HspIdentity:    intPtr(18),
									HspPositive:    intPtr(18),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(18),
									Density:        nil,
									QuerySeq:       []byte("ACAGAATGTCGAACTATA"),
									SubjectSeq:     []byte("ACAGAATGTCGAACTATA"),
									FormatMidline:  []byte("||||||||||||||||||"),
								},
							},
						},
						{
							N:         24,
							Id:        "gi|356871506|emb|FO082053.1|",
							Def:       "Pichia sorbitophila strain CBS 7064 chromosome G complete sequence",
							Accession: "FO082053",
							Len:       1423303,
							Hsps: []blast.Hsp{
								{
									N:              1,
									BitScore:       32.2105,
									Score:          16,
									EValue:         106.294,
									QueryFrom:      13,
									QueryTo:        28,
									HitFrom:        61730,
									HitTo:          61745,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(1),
									HspIdentity:    intPtr(16),
									HspPositive:    intPtr(16),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(16),
									Density:        nil,
									QuerySeq:       []byte("ACTATACGACGAGCAC"),
									SubjectSeq:     []byte("ACTATACGACGAGCAC"),
									FormatMidline:  []byte("||||||||||||||||"),
								},
							},
						},
						{
							N:         25,
							Id:        "gi|353230524|emb|HE601625.1|",
							Def:       "Schistosoma mansoni strain Puerto Rico chromosome 2, complete genome",
							Accession: "HE601625",
							Len:       34464480,
							Hsps: []blast.Hsp{
								{
									N:              1,
									BitScore:       32.2105,
									Score:          16,
									EValue:         106.294,
									QueryFrom:      1,
									QueryTo:        16,
									HitFrom:        28173004,
									HitTo:          28173019,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(1),
									HspIdentity:    intPtr(16),
									HspPositive:    intPtr(16),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(16),
									Density:        nil,
									QuerySeq:       []byte("ACAGAATGTCGAACTA"),
									SubjectSeq:     []byte("ACAGAATGTCGAACTA"),
									FormatMidline:  []byte("||||||||||||||||"),
								},
								{
									N:              2,
									BitScore:       32.2105,
									Score:          16,
									EValue:         106.294,
									QueryFrom:      3,
									QueryTo:        18,
									HitFrom:        28996063,
									HitTo:          28996048,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(-1),
									HspIdentity:    intPtr(16),
									HspPositive:    intPtr(16),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(16),
									Density:        nil,
									QuerySeq:       []byte("AGAATGTCGAACTATA"),
									SubjectSeq:     []byte("AGAATGTCGAACTATA"),
									FormatMidline:  []byte("||||||||||||||||"),
								},
							},
						},
						{
							N:         26,
							Id:        "gi|341821300|emb|HE576794.1|",
							Def:       "Megasphaera elsdenii strain DSM 20460 draft genome",
							Accession: "HE576794",
							Len:       2474718,
							Hsps: []blast.Hsp{
								{
									N:              1,
									BitScore:       32.2105,
									Score:          16,
									EValue:         106.294,
									QueryFrom:      14,
									QueryTo:        29,
									HitFrom:        1741778,
									HitTo:          1741793,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(1),
									HspIdentity:    intPtr(16),
									HspPositive:    intPtr(16),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(16),
									Density:        nil,
									QuerySeq:       []byte("CTATACGACGAGCACT"),
									SubjectSeq:     []byte("CTATACGACGAGCACT"),
									FormatMidline:  []byte("||||||||||||||||"),
								},
							},
						},
					},
					Statistics: &blast.Statistics{
						DbNum:    17331862,
						DbLen:    1419046940,
						HspLen:   0,
						EffSpace: 0,
						Kappa:    0.710603,
						Lambda:   1.37406,
						Entropy:  1.30725,
					},
					Message: nil,
				},
			},
			MegaStatistics: nil,
		},
		cf:        func(w, h vg.Length) vg.Canvas { return vgsvg.New(w, h) },
		configure: true,
		legend:    true,
		aligns:    true,
		depths:    false,
		golden:    "legends_align.svg",
	},
	{
		in: blast.Output{
			Program:   "blastn",
			Version:   "BLASTN 2.2.27+",
			Reference: "Stephen F. Altschul, Thomas L. Madden, Alejandro A. Sch&auml;ffer, Jinghui Zhang, Zheng Zhang, Webb Miller, and David J. Lipman (1997), \"Gapped BLAST and PSI-BLAST: a new generation of protein database search programs\", Nucleic Acids Res. 25:3389-3402.",
			Database:  "nr",
			QueryId:   "33421",
			QueryDef:  "No definition line",
			QueryLen:  32,
			QuerSeq:   nil,
			Parameters: blast.Parameters{
				MatrixName:  nil,
				Expect:      1000,
				Include:     nil,
				Match:       intPtr(1),
				Mismatch:    intPtr(-3),
				GapOpen:     5,
				GapExtend:   2,
				Filter:      stringPtr("F"),
				PhiPattern:  nil,
				EntrezQuery: nil,
			},
			Iterations: []blast.Iteration{
				{
					N:        1,
					QueryId:  stringPtr("33421"),
					QueryDef: stringPtr("No definition line"),
					QueryLen: intPtr(32),
					Hits: []blast.Hit{
						{
							N:         1,
							Id:        "gi|388525227|gb|CP003531.1|",
							Def:       "Thermogladius cellulolyticus 1633, complete genome",
							Accession: "CP003531",
							Len:       1356318,
							Hsps: []blast.Hsp{
								{
									N:              1,
									BitScore:       38.1576,
									Score:          19,
									EValue:         1.72292,
									QueryFrom:      7,
									QueryTo:        29,
									HitFrom:        1187458,
									HitTo:          1187436,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(-1),
									HspIdentity:    intPtr(22),
									HspPositive:    intPtr(22),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(23),
									Density:        nil,
									QuerySeq:       []byte("TGTCGAACTATACGACGAGCACT"),
									SubjectSeq:     []byte("TGTCGAGCTATACGACGAGCACT"),
									FormatMidline:  []byte("|||||| ||||||||||||||||"),
								},
							},
						},
						{
							N:         2,
							Id:        "gi|354799811|gb|JN964312.1|",
							Def:       "Mus musculus targeted non-conditional, lacZ-tagged mutant allele Morn4:tm1e(KOMP)Wtsi; transgenic",
							Accession: "JN964312",
							Len:       40247,
							Hsps: []blast.Hsp{
								{
									N:              1,
									BitScore:       36.1753,
									Score:          18,
									EValue:         6.80792,
									QueryFrom:      1,
									QueryTo:        18,
									HitFrom:        26580,
									HitTo:          26597,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(1),
									HspIdentity:    intPtr(18),
									HspPositive:    intPtr(18),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(18),
									Density:        nil,
									QuerySeq:       []byte("ACAGAATGTCGAACTATA"),
									SubjectSeq:     []byte("ACAGAATGTCGAACTATA"),
									FormatMidline:  []byte("||||||||||||||||||"),
								},
							},
						},
						{
							N:         24,
							Id:        "gi|356871506|emb|FO082053.1|",
							Def:       "Pichia sorbitophila strain CBS 7064 chromosome G complete sequence",
							Accession: "FO082053",
							Len:       1423303,
							Hsps: []blast.Hsp{
								{
									N:              1,
									BitScore:       32.2105,
									Score:          16,
									EValue:         106.294,
									QueryFrom:      13,
									QueryTo:        28,
									HitFrom:        61730,
									HitTo:          61745,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(1),
									HspIdentity:    intPtr(16),
									HspPositive:    intPtr(16),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(16),
									Density:        nil,
									QuerySeq:       []byte("ACTATACGACGAGCAC"),
									SubjectSeq:     []byte("ACTATACGACGAGCAC"),
									FormatMidline:  []byte("||||||||||||||||"),
								},
							},
						},
						{
							N:         25,
							Id:        "gi|353230524|emb|HE601625.1|",
							Def:       "Schistosoma mansoni strain Puerto Rico chromosome 2, complete genome",
							Accession: "HE601625",
							Len:       34464480,
							Hsps: []blast.Hsp{
								{
									N:              1,
									BitScore:       32.2105,
									Score:          16,
									EValue:         106.294,
									QueryFrom:      1,
									QueryTo:        16,
									HitFrom:        28173004,
									HitTo:          28173019,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(1),
									HspIdentity:    intPtr(16),
									HspPositive:    intPtr(16),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(16),
									Density:        nil,
									QuerySeq:       []byte("ACAGAATGTCGAACTA"),
									SubjectSeq:     []byte("ACAGAATGTCGAACTA"),
									FormatMidline:  []byte("||||||||||||||||"),
								},
								{
									N:              2,
									BitScore:       32.2105,
									Score:          16,
									EValue:         106.294,
									QueryFrom:      3,
									QueryTo:        18,
									HitFrom:        28996063,
									HitTo:          28996048,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(-1),
									HspIdentity:    intPtr(16),
									HspPositive:    intPtr(16),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(16),
									Density:        nil,
									QuerySeq:       []byte("AGAATGTCGAACTATA"),
									SubjectSeq:     []byte("AGAATGTCGAACTATA"),
									FormatMidline:  []byte("||||||||||||||||"),
								},
							},
						},
						{
							N:         26,
							Id:        "gi|341821300|emb|HE576794.1|",
							Def:       "Megasphaera elsdenii strain DSM 20460 draft genome",
							Accession: "HE576794",
							Len:       2474718,
							Hsps: []blast.Hsp{
								{
									N:              1,
									BitScore:       32.2105,
									Score:          16,
									EValue:         106.294,
									QueryFrom:      14,
									QueryTo:        29,
									HitFrom:        1741778,
									HitTo:          1741793,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(1),
									HspIdentity:    intPtr(16),
									HspPositive:    intPtr(16),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(16),
									Density:        nil,
									QuerySeq:       []byte("CTATACGACGAGCACT"),
									SubjectSeq:     []byte("CTATACGACGAGCACT"),
									FormatMidline:  []byte("||||||||||||||||"),
								},
							},
						},
					},
					Statistics: &blast.Statistics{
						DbNum:    17331862,
						DbLen:    1419046940,
						HspLen:   0,
						EffSpace: 0,
						Kappa:    0.710603,
						Lambda:   1.37406,
						Entropy:  1.30725,
					},
					Message: nil,
				},
			},
			MegaStatistics: nil,
		},
		cf:        func(w, h vg.Length) vg.Canvas { return vgsvg.New(w, h) },
		configure: true,
		legend:    false,
		aligns:    true,
		depths:    false,
		golden:    "aligns.svg",
	},
	{
		in: blast.Output{
			Program:   "blastn",
			Version:   "BLASTN 2.2.27+",
			Reference: "Stephen F. Altschul, Thomas L. Madden, Alejandro A. Sch&auml;ffer, Jinghui Zhang, Zheng Zhang, Webb Miller, and David J. Lipman (1997), \"Gapped BLAST and PSI-BLAST: a new generation of protein database search programs\", Nucleic Acids Res. 25:3389-3402.",
			Database:  "nr",
			QueryId:   "33421",
			QueryDef:  "No definition line",
			QueryLen:  32,
			QuerSeq:   nil,
			Parameters: blast.Parameters{
				MatrixName:  nil,
				Expect:      1000,
				Include:     nil,
				Match:       intPtr(1),
				Mismatch:    intPtr(-3),
				GapOpen:     5,
				GapExtend:   2,
				Filter:      stringPtr("F"),
				PhiPattern:  nil,
				EntrezQuery: nil,
			},
			Iterations: []blast.Iteration{
				{
					N:        1,
					QueryId:  stringPtr("33421"),
					QueryDef: stringPtr("No definition line"),
					QueryLen: intPtr(32),
					Hits: []blast.Hit{
						{
							N:         1,
							Id:        "gi|388525227|gb|CP003531.1|",
							Def:       "Thermogladius cellulolyticus 1633, complete genome",
							Accession: "CP003531",
							Len:       1356318,
							Hsps: []blast.Hsp{
								{
									N:              1,
									BitScore:       38.1576,
									Score:          19,
									EValue:         1.72292,
									QueryFrom:      7,
									QueryTo:        29,
									HitFrom:        1187458,
									HitTo:          1187436,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(-1),
									HspIdentity:    intPtr(22),
									HspPositive:    intPtr(22),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(23),
									Density:        nil,
									QuerySeq:       []byte("TGTCGAACTATACGACGAGCACT"),
									SubjectSeq:     []byte("TGTCGAGCTATACGACGAGCACT"),
									FormatMidline:  []byte("|||||| ||||||||||||||||"),
								},
							},
						},
						{
							N:         2,
							Id:        "gi|354799811|gb|JN964312.1|",
							Def:       "Mus musculus targeted non-conditional, lacZ-tagged mutant allele Morn4:tm1e(KOMP)Wtsi; transgenic",
							Accession: "JN964312",
							Len:       40247,
							Hsps: []blast.Hsp{
								{
									N:              1,
									BitScore:       36.1753,
									Score:          18,
									EValue:         6.80792,
									QueryFrom:      1,
									QueryTo:        18,
									HitFrom:        26580,
									HitTo:          26597,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(1),
									HspIdentity:    intPtr(18),
									HspPositive:    intPtr(18),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(18),
									Density:        nil,
									QuerySeq:       []byte("ACAGAATGTCGAACTATA"),
									SubjectSeq:     []byte("ACAGAATGTCGAACTATA"),
									FormatMidline:  []byte("||||||||||||||||||"),
								},
							},
						},
						{
							N:         24,
							Id:        "gi|356871506|emb|FO082053.1|",
							Def:       "Pichia sorbitophila strain CBS 7064 chromosome G complete sequence",
							Accession: "FO082053",
							Len:       1423303,
							Hsps: []blast.Hsp{
								{
									N:              1,
									BitScore:       32.2105,
									Score:          16,
									EValue:         106.294,
									QueryFrom:      13,
									QueryTo:        28,
									HitFrom:        61730,
									HitTo:          61745,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(1),
									HspIdentity:    intPtr(16),
									HspPositive:    intPtr(16),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(16),
									Density:        nil,
									QuerySeq:       []byte("ACTATACGACGAGCAC"),
									SubjectSeq:     []byte("ACTATACGACGAGCAC"),
									FormatMidline:  []byte("||||||||||||||||"),
								},
							},
						},
						{
							N:         25,
							Id:        "gi|353230524|emb|HE601625.1|",
							Def:       "Schistosoma mansoni strain Puerto Rico chromosome 2, complete genome",
							Accession: "HE601625",
							Len:       34464480,
							Hsps: []blast.Hsp{
								{
									N:              1,
									BitScore:       32.2105,
									Score:          16,
									EValue:         106.294,
									QueryFrom:      1,
									QueryTo:        16,
									HitFrom:        28173004,
									HitTo:          28173019,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(1),
									HspIdentity:    intPtr(16),
									HspPositive:    intPtr(16),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(16),
									Density:        nil,
									QuerySeq:       []byte("ACAGAATGTCGAACTA"),
									SubjectSeq:     []byte("ACAGAATGTCGAACTA"),
									FormatMidline:  []byte("||||||||||||||||"),
								},
								{
									N:              2,
									BitScore:       32.2105,
									Score:          16,
									EValue:         106.294,
									QueryFrom:      3,
									QueryTo:        18,
									HitFrom:        28996063,
									HitTo:          28996048,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(-1),
									HspIdentity:    intPtr(16),
									HspPositive:    intPtr(16),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(16),
									Density:        nil,
									QuerySeq:       []byte("AGAATGTCGAACTATA"),
									SubjectSeq:     []byte("AGAATGTCGAACTATA"),
									FormatMidline:  []byte("||||||||||||||||"),
								},
							},
						},
						{
							N:         26,
							Id:        "gi|341821300|emb|HE576794.1|",
							Def:       "Megasphaera elsdenii strain DSM 20460 draft genome",
							Accession: "HE576794",
							Len:       2474718,
							Hsps: []blast.Hsp{
								{
									N:              1,
									BitScore:       32.2105,
									Score:          16,
									EValue:         106.294,
									QueryFrom:      14,
									QueryTo:        29,
									HitFrom:        1741778,
									HitTo:          1741793,
									PhiPatternFrom: nil,
									PhiPatternTo:   nil,
									QueryFrame:     intPtr(1),
									HitFrame:       intPtr(1),
									HspIdentity:    intPtr(16),
									HspPositive:    intPtr(16),
									HspGaps:        intPtr(0),
									AlignLen:       intPtr(16),
									Density:        nil,
									QuerySeq:       []byte("CTATACGACGAGCACT"),
									SubjectSeq:     []byte("CTATACGACGAGCACT"),
									FormatMidline:  []byte("||||||||||||||||"),
								},
							},
						},
					},
					Statistics: &blast.Statistics{
						DbNum:    17331862,
						DbLen:    1419046940,
						HspLen:   0,
						EffSpace: 0,
						Kappa:    0.710603,
						Lambda:   1.37406,
						Entropy:  1.30725,
					},
					Message: nil,
				},
			},
			MegaStatistics: nil,
		},
		cf:        func(w, h vg.Length) vg.Canvas { return vgsvg.New(w, h) },
		configure: true,
		legend:    true,
		aligns:    false,
		depths:    false,
		golden:    "legend.svg",
	},
	{
		in: blast.Output{
			Program:   "blastn",
			Version:   "BLASTN 2.2.27+",
			Reference: "Stephen F. Altschul, Thomas L. Madden, Alejandro A. Sch&auml;ffer, Jinghui Zhang, Zheng Zhang, Webb Miller, and David J. Lipman (1997), \"Gapped BLAST and PSI-BLAST: a new generation of protein database search programs\", Nucleic Acids Res. 25:3389-3402.",
			Database:  "nr",
			QueryId:   "33421",
			QueryDef:  "No definition line",
			QueryLen:  32,
			QuerSeq:   nil,
			Parameters: blast.Parameters{
				MatrixName:  nil,
				Expect:      1000,
				Include:     nil,
				Match:       intPtr(1),
				Mismatch:    intPtr(-3),
				GapOpen:     5,
				GapExtend:   2,
				Filter:      stringPtr("F"),
				PhiPattern:  nil,
				EntrezQuery: nil,
			},
			Iterations:     nil,
			MegaStatistics: nil,
		},
		cf:     func(w, h vg.Length) vg.Canvas { return vgsvg.New(w, h) },
		golden: "no-results.svg",
	},
	{
		in:     blast.Output{},
		cf:     func(w, h vg.Length) vg.Canvas { return vgsvg.New(w, h) },
		golden: "empty-input.svg",
	},
}

func (s *S) TestSummary(c *check.C) {
	for _, t := range testOutputs {
		sum := graphic.NewSummary(t.in)
		if t.configure {
			sum.Legend = t.legend
			sum.Aligns = t.aligns
			sum.Depths = t.depths
		}
		var b bytes.Buffer
		sum.Render(t.cf).(io.WriterTo).WriteTo(&b)
		if *regen {
			c.Assert(ioutil.WriteFile(filepath.Join("testdata", t.golden), b.Bytes(), 0664), check.Equals, nil)
			continue
		}
		want, err := ioutil.ReadFile(filepath.Join("testdata", t.golden))
		c.Assert(err, check.Equals, nil)
		c.Check(b.Bytes(), check.DeepEquals, want)
	}
}
